Don't assume that all notifications are NotifySlotChange
LudovicRousseau/CCID pull request #154
Opened 2024-12-12 14:13 UTC by bluetech

CCID defines another type of message type on the interrupt pipe,
HardwareError, and others may also be conceivably sent. So check the
message type instead of assuming it's a NotifySlotChange.

While at it, I added debug logging of HardwareError, it might be useful
for someone.

Note 1: I recommend viewing the second commit ignoring whitespace, it makes the diff clearer.

Note 2: I don't have a multi-slot reader, so I wasn't able to test the `Multi_` code paths.

2024-12-12 20:53 UTC, LudovicRousseau requested changes

2024-12-12 20:53 UTC, LudovicRousseau commented on src/ccid.h
> +/* Known CCID bMessageType values. */
Do not use `enum` if it makes no sens.
I prefer `#define` in this case since all the values are hardcoded.

2024-12-12 20:53 UTC, LudovicRousseau commented on src/ccid.h
> +	CCID_MESSAGE_TYPE_PC_to_RDR_IccPowerOn = 0x62,
Remove the `CCID_MESSAGE_TYPE_` prefix.
`PC_to_RDR_IccPowerOn` is good enough.

2024-12-12 21:18 UTC, LudovicRousseau commented
I like your changes. It is good work.

2024-12-13 08:27 UTC, bluetech commented
Thanks for the review, I addressed your comments.

2024-12-13 12:53 UTC, LudovicRousseau commented on src/ccid_usb.c
> +				}
I would add something like:
```
default:
    DEBUG_XXD("Unknown bMessageType: ", buffer, actual_length);
````

2024-12-13 13:36 UTC, bluetech commented
I added the `default` cases. I used the message "Unrecognized notification", since "Unknown bMessageType" is a bit ambiguous.

2024-12-13 17:38 UTC, merged

2024-12-13 17:38 UTC, LudovicRousseau commented
Thanks